### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by Mailaender** [willuhn/hbci4java#42]
Die Versionsnummer nie zu erhöhen und einfach in den commit messags Änderungen anzugeben ist ein Alptraum für Linux Paketierer. https://github.com/willuhn/hibiscus/commits/master/lib/hbci4java-2.5.12.jar

Auch die Tatsache, dass man den Quelltext in einem ganz anderen Repository findet https://github.com/willuhn/hibiscus/tree/master/lib.src wiederum aber nicht in dessen *.src.zip Archiv ist hoch ungewöhnlich.

Unter https://github.com/blog/1547-release-your-software wird der Goldstandard zur Veröffentlichung erklärt.

Hintergrund: Ich versuche Hibiscus in @openSUSE zu paketieren und dafür muss _alles_ vom Quelltext gebaut werden.

**Comment by willuhn** [comment]
Das iegt einfach daran, weil es von HBCI4Java gar keine Releases in dem Sinne gibt. Ich plane auch nicht, welche zu machen. Ehrlich gesagt, fehlt mir schlicht die Zeit fuer ein sauberes Release-Management von HBCI4Java. Ich nutze das Github-Repo lediglich, um den Quellcode zu verwalten und damit ihn Interessierte nutzen/forken koennen.

Warum versuchst du eigentlich, Hibiscus zu paketieren? Unter http://software.opensuse.org/package/hibiscus gibt es doch schon mehrere Pakete.

**Comment by Mailaender** [comment]
Ja, das sind meine, aber die werden nie so außerhalb der Benutzer-Paketquellen akzeptiert werden. Ich verzweifle hier wirklich an den Bau-Instruktionen: In den Ordner mit `build.xml` wechseln wo diese Datei in `hbci4java-2.5.12-src.zip` überhaupt nicht enthalten ist.

**Comment by kicktipp** [comment]
Ich finde, dass er völlig recht hat. Warum kann nicht das Repo auch
gleich den maven build anstoßen? Dann muss wohl auch ein neuer Paketname
her usw. Aber das ganze Ding lockt keine neuen Entwickler an, wenn es
nicht einfach zu forken zu bauen und zu releasen ist.

Letztlich muss einfach jede Änderung am Sourcecode direkt als Paket auf 
maven central landen inkl Source Code.

Ich kann mich da gerne mal versuchen, wenn das gewünscht ist.

Gruß
Janning

Am 28.12.2015 um 15:40 schrieb Olaf Willuhn:

**Comment by willuhn** [comment]
Du kannst dich da gern dran versuchen, wenn du willst. Wichtig ist aber, dass auch die nativen JNI-Libs fuer den CTAPI-Code mit compiliert werden koennen.

**Comment by Mailaender** [comment]
https://build.opensuse.org/package/show/home:Mailaender:branches:Java:packages/hbci4java baut endlich durch, aber es war wirklich umständlicher als nötig.

**Comment by Mailaender** [comment]
Wie kompiliert man die `libhbci4java-sizrdh-linux-gcc*.so` Bibliothek?

**Comment by Mailaender** [comment]
Und woher stammt `libct.so`?

**Comment by willuhn** [comment]
Die sizrdh-Lib stammt von hier: http://hbci4java.kapott.org/index.html
Das ist die urspruengliche Webseite von HBCI4Java von Stefan Palme (siehe auch der Absatz "Entstehung" unter https://github.com/willuhn/hbci4java). Stefan konnte sie damals nur nach Unterzeichnung eines NDA implementieren - der Source durfte nicht oeffentlich gemacht werden. Die Datei wird benoetigt, um Schluesseldateien im SIZ-RDH-Format lesen zu koennen. Ob die in der Praxis ueberhaupt noch Verwendung finden, weiss ich nicht.

Die libct.so ist eine aeltere Version des CTAPI-Treibers von Kobil (siehe https://www.willuhn.de/wiki/doku.php?id=support:list:kartenleser#kobil), den ich damals nach Rueckfrage bei Kobil beilegen durfte. Vermutlich gibt es nur noch wenige Hibiscus-Installationen, bei denen diese Datei tatsaechlich noch genutzt wird.

**Comment by willuhn** [comment]
Wir reden hier aber von zwei verschiedenen Themen im selben Ticket. "kicktipp" geht es darum, HBCI4Java per oeffentlichem Maven-Repo verfuegbar zu machen und dir darum, Hibiscus fuer OpenSuSE zu paketieren. Das hier ist das Github-Repo von HBCI4Java.

**Comment by kicktipp** [comment]
Wenn das niemand oder nur noch wenige benutzen, dann raus mit den Libs.

Das ganze Projekt muss viel simpler werden, das wäre ein erster Schritt. 
Aber natürlich muss dafür die Unterstützung vorhanden sein.

Auch ist ja Stefan Palme wohl nicht mehr erreichbar wie ich aus den 
Threads rauslese. Stimmt das?

Olaf, Du solltest das Projekt fortführen als Projektleiter (das bist Du 
ja quasi eh schon). Der ganze Fork ist ja auch schon ein paar Jahre alt.

Mein Vorschlag wäre:
- Neuer Paketname wie org.hbci4java oder org.hbci4j
- Alles maven repo fähig machen
- Alte Libs die nicht OpenSource sind rauswerfen.

Das Thema hibiscus ist wiederum ein anderes. Damit kenne ich mich nicht 
aus. Ich nutze hbci4java als Lib in meinen Projekten.

Die ersten Schritte traue ich mir durchaus zu, nur habe ich kein 
tieferes Verständnis von hbci leider. Daher weiß ich nicht, ob ich das 
hinbekomme. Ich kann mich da aber gerne einbringen. Ich habe neulich 
erste ein anderes Projekt fit für maven central gemacht.

Gruß
Janning


Am 29.12.2015 um 10:35 schrieb Olaf Willuhn:

**Comment by Mailaender** [comment]
Maven Central ist sicherlich eine sinnvolle Lösung gerade, wenn man die Weiterverwendbarkeit in anderen Projekten sicherstellen möchte. Mit https://mizdebsk.fedorapeople.org/xmvn/ gibt es auch eine Möglichkeit das zu paketieren. Ich habe es nur noch nicht zum Laufen gebracht. Mir würden einfache source tarballs mit einer build.xml für `ant` schon reichen. Und ja: altertümliche .so Dateien ohne Quelltext sind intransparent und müssen raus.

**Comment by asbachb** [comment]
Generell würde es vielleicht Sinn machen eine hbci4j-Organisation zu erstellen. Aktuell sind ja auch mehrere Projekte innerhalb des Projekts abgelegt. z.B. die cryptalgs4java-Geschichte. Aus meiner Sicht würde es auch Sinn machen die Teile die auf jni etc. pp. zugreifen zu isolieren und in ein eigenes Modul zu packen.

Gibt es denn generell Interesse daran, das Projekt "aufzuräumen"?

**Comment by shred** [comment]
Ein neuer Paketname nebst passender Domain (eine CNO-Domain würde ich auch sponsorn) wäre sinnvoll, da man meines Wissens die Domain zum Paketnamen besitzen muss, um Pakete bei Maven Central veröffentlichen zu dürfen. Allerdings kämen wir dann auch um ein richtiges Release-Management mit Versionsnummern nicht mehr herum.

Ich würde den Quelltext bei der Gelegenheit auch allzu gerne mal durch einen Formatter schicken. Momentan ist es ein bunter Mix aus verschiedenen Formatstilen, Tabs und Spaces... :-)

**Comment by code-chris** [comment]
Ist das hier noch aktuell? Scheint ja ein grundsätzliches Interesse und Arbeitsbereitschaft (auch meinerseits) da zu sein...

Vielleicht sollte einfach mal eine Art Roadmap erarbeitet werden mit Schritten die durchgeführt werden müssten um die genannten Ziele zu erreichen.

**Comment by asbachb** [comment]
Aktuell sehe ich zwei Möglichkeiten:

#1: Da die aktuelle Entwicklung hier im Repository von @willuhn stattfindet (und er in der Vergangenheit ja die treibende Kraft hinter dem Projekt war), wäre es nicht schlecht, wenn er sich dazu äußern würde, wie er sich das in Zukunft vorstellt.

#2: Man macht einen Fork in dem sich Leute organisieren, die veruschen möchten den Codestand auf ein anderes Fundament zu heben und eventuell ein paar Sachen über board werfen (z.B. die Binaries)

**Comment by willuhn** [comment]
Wie ich schon mehrfach schrieb: Wenn ihr Sachen ändern wollt, immer her mit den Pull-Requests. Wichtig ist aber, dass die Kompatibilität mit existierender Software nicht gebrochen wird.

HBCI4Java ist als Bibliothek in so einigen Anwendungen (teils sicher auch in rein Firmen-internen) integriert. Ich fänd es nicht sinnvoll, nur der Schönheit des Codes wegen mit der Abwärtskompatibilität zu brechen. Mir ist klar, dass der Package-Name "org.kapott" nicht der Schönste ist. Das war aber halt damals Stefans Entscheidung. Würde man das jetzt ändern, gehen ALLE Integrationen kaputt. Auch die Banking-Anwendung Pecunia z.Bsp. Sicher kann man das per Refaktoring in der eigenen Anwendung schnell korrigieren. Aber es erzeugt jede Menge Fehlermails von Nutzern (die dann alle bei mir aufschlagen) und unter Umständen irreparabel kaputte Anwendungen (wenn der Autor, der vor Jahren mal die HBCI4Java-Anbindung geschrieben hat, diese nicht mehr pflegt).

Das aber nur als Beispiel. Hier werden immer wieder Sachen genannt, was "man" denn alles mal so machen könnte:

- Einmal komplett den ganzen Code durchformatieren (meine Güte, ist das wirklich das Wichtigste?)
- Build-Scripts überarbeiten
- nicht mehr benötigten Code entfernen
- Native Libs mit unklarer Lizenz entfernen
- Copyright-Info in jeder Quellcode-Datei nachtragen
- Releases
- Anbindung an Maven-Repository
 
Und bei der Frage, wer es denn machen möchte, treten gefühlt alle einen Schritt zurück.
 
Für mich ist HBCI4Java ein reines Mittel zum Zweck. Mein Zweck heisst "Hibiscus". Und die Sachen, die ich wichtig finde, sind notwendige Aktualisierungen bei den SEPA-Themen:
 
- Bis Ende des Jahres brauchen wir Unterstützung für die neuen PAIN-Formate aus SEPA 3 (http://www.ebics.de/index.php?id=77)
- Die Implementierung von camt.053 zum Abruf der Umsätze über das neue SEPA-Format (MT940 wird es nicht ewig geben)
 
Das sind doch eigentlich die Themen, die wichtig sind, oder?
 
Lange Rede, kurzer Sinn: HBCI4Java ist inzwischen LGPL. Wenn ihr Aufräum-Arbeiten am Code machen wollt, nur zu - von mir aus auch als Fork. Ihr müsst da nicht auf mein OK warten. Ich will nur nicht, dass die Tasks alle bei mir abgekippt werden. Denn für meinen Zweck "Hibiscus" brauche ich die oben genannten Aufräumarbeiten nicht.

**Comment by code-chris** [comment]
@willuhn: Keiner von uns hier möchte dich oder deine bisherige Arbeit mit hbci4java angreifen!

Die Abwärtskompatibilität ist wie bei allen Libraries mit einigen Verwendungen ein Problem. Allerdings lässt sich das mit einem nebenläufigen Branching-Konzept (2.x, 3.x, 3.1.x, ...) zumindest zum Teil in Griff bekommen, da große Strukturänderungen dann in Major-Releases gemacht werden können und alte Release-Zeige dann nur noch notwendige Bugfixes oder nicht allzu aufwändige neue Features erhalten. Das sehe ich zumindest als Kompromisslösung.

Ich finde, dass es grundsätzlich immer mindestens zwei Gesichtspunkte bei der Entwicklung von Software geben muss:
- Funktionen
- Infrastruktur (Build-System, Code-Style, Release-Management, Lizenzen, ...)

Das Problem bei fehlender oder veralteter Infrastruktur ist v.a. die Integration der Library mit neueren Endanwendungen. Für solche ist die Library dann uninteressant (aber nicht, weil sie nicht die gewünschten Funktionen bieten würde).

Die Überführung der Lib (sofern das mit der Abwärtskompatibilität möglich ist) in ein Repo innerhalb einer GitHub-Organisation würde auch die Arbeitslast eher teilen. Es ist dann einfacher, dass mehrere Leute am Code arbeiten können. Dann könnte auch eher auf Aufgabengebiete aufgeteilt werden wie eben Code-Stylings und eben wirklich wichtige Funktionen wie neue SEPA-Spezifikationen.

Was denkt denn ihr? (Die noch interessiert sind)

**Comment by willuhn** [comment]
Keine Bange, ich habe mich nicht angegriffen gefühlt. Ehrlich. Ich will nur deutlich machen, dass diese Cleanup-Themen für mich persönlich keine Priorität haben. Wenn es euch wichtig ist - reicht wie gesagt Patches ein.  Aber auf meiner persönlichen TODO-Liste stehen Themen wie SEPA 3.0 und CAMT deutlich weiter vorn. Denn das sind die Sachen, die ich in Hibiscus brauchen werde. Releases brauche ich - zumindest für Hibiscus - nicht.

**Comment by asbachb** [comment]
Also grundsätzlich hätte ich schon Interesse daran, was zum aufräumen und der Infrastruktur beizutragen (hatte auch schon mal in einem Branch angefangen: https://github.com/asbachb/hbci4java/tree/cleanup - Fachlich aktuell eher weniger, weil ich mich noch nicht sonderlich intensiv mit der API beschäftigt habe.

Die Idee mit der Organisation finde ich auch sinnvoll, da man dort einfacher das Projekt modularisieren könnte. Damit das Ganze dann weniger verwirrend ist, könnte man die aktuelle Entwicklung (dieses Modul) dorthin ziehen. Falls es noch neue Funktionalitäten gibt, müssten die halt dort reingemerged werden.
Ich würde es mir jetzt aber nicht Anmaßen ohne "go" von @willuhn eine Organisation mit dem Namen hbci4java zu erstellen... 

Alternativ könnte man in meinem Branch weitermachen, bis da was halbwegs sinnvolles bei rumgekommen ist - Interessierten würde ich entsprechende Schreibberechtigungen erteilen. Wäre wahrscheinlich kurzfristig die beste Lösung? Nicht, dass wir jetzt ein großes Fass aufmachen und nach einer Woche verläuft sich die ganze Geschichte wieder... ;)

**Comment by kicktipp** [comment]
Schöne Antwort von Olaf. Schön, das du dich nicht angegriffen fühlst. Den 
das hat auch niemand so gemeint.

Und natürlich sind die Funktionen sehr wichtig. Für uns kann aber das 
Projekt jetzt schon alles was wir jemals brauchen werden. Aber das Projekt 
zu verwenden ist nicht einfach.

Ich denke dass eine gute Infrastruktur extrem wichtig ist für ein Open 
Source Projekt. Vor allem, wenn man möchte, das auch mal andere als Olaf 
etwas weiterentwickeln.

Dazu muss man dann eben auch mal einen Schritt machen, der nicht mehr 
abwärtskompatibel ist.

Ich kann gerne helfen.

Gruß
Janning



Am 1. August 2016 5:50:28 nachm. schrieb Olaf Willuhn 
<notifications@github.com>:

**Comment by willuhn** [comment]
Also von mir aus könnt ihr eine hbci4java-Organisation bei Github erstellen. Der Sinn einer solchen Organisation ist ja eben, dass es nicht mehr eine einzelne Person ist. Ob ich die Organisation jetzt anlege oder einer von euch, spielt doch da sicher keine Rolle.

@asbachb Sehe ich das richtig, dass du in deinem Fork den kompletten Chipkarten-Support per CTAPI entfernt hast?

**Comment by asbachb** [comment]
@willuhn das ist korrekt. Hatte geplant, die Funktionalität in ein eigenes Modul auszulagern - Auch vor dem Hintergrund, dass die Lizenz der binären Treiber (nach meinem aktuellen Stand) unklar ist.
