### ISSUE TITLE
Ist es mit hbci4java möglich SEPA Basis Lastschriften einzuziehen/auszuführen?

### ISSUE THREAD

**Issue by PatrickHuetter** [willuhn/hbci4java#44]
Hi zusammen,
ich baue aktuell für mich selbst eine Rechnungs & Abrechnungssoftware, die möglichst automatisiert SEPA Lastschriften von meinen Kunden einzuziehen soll. 

Insgesamt habe ich mich das Verfahren wie folgt vorgestellt:
1) Rechnung wird generiert und an den Kunden geschickt mit der Info "Der Rechnungsbetrag wird in den kommenden 3-4 Tagen von Ihrem Konto abgebucht".
2) 3 Tage nach Rechnungsversand soll meine Java-Abrechnungs-Software automatisch den Betrag via HBCI als Sepa Basislastschrift bei der Bank einreichen und somit ausführen lassen.

Hierfür habe ich mir ein Geschäftskonto bei der Deutschen Bank eingerichtet, da diese FinTS und HBCI+ supportet und bereits alles was SEPA Lastschriften angeht, geklärt.

Nun die Frage, ob es möglich ist, mit dieser Bibliothek SEPA Lastschriften auszuführen und wenn ja, ob es irgendwo eine Dokumentation dafür gibt?

Alternativ habe ich noch einen Plan B mit dem ich diesen Prozess anderweitig automatisieren kann (ohne HBCI), die HBCI Lösung wäre mir jedoch lieber.

**Comment by shred** [comment]
Das geht, wir benutzen hbci4java in der Firma genau für diesen Zweck.

Zu deinem Punkt 2: SEPA-Lastschriften lassen sich nicht "per sofort" ausführen, sondern das Ausführungsdatum muss (wenn ich mich richtig erinnere) mindestens 4 Werktage in der Zukunft liegen. Du müsstest die Lastschrift also schon bei Punkt 1 zur Bank übertragen, mit einem entsprechenden Ausführungsdatum. Ein zu frühes Datum korrigiert unsere Bank entsprechend nach hinten, andere Banken könnten die Lastschrift aber auch zurückweisen.

**Comment by scaratec** [comment]
Ich hatte einen ähnlichen Anwendungsfall. Ich generiere mit hbci4java eine XML-Datei die ich über das Portal der Sparkasse einreiche. Dann werden die Lastschriften abgebucht. Im Wesentlichen läuft das so, wie Du es beschrieben hast. Ausser, dass die Lastschriften nicht automatisch per FinTS oder so eingereicht, sondern manuell hochgeladen werden. 

Bisher konnte ich mich auch zeitlichen Gründen noch nicht darum kümmern, das weiter zu automatisieren. Generell sollte das aber möglich sein. Ich weiß nur, nicht, wie das hinterher noch mit der Autorisierung läuft. Bei meinem Weg muss ich noch eine TAN eingeben. Das müssten bei Deinem Wunschweg ja über FinTS / HBCI+ abgewickelt werden. Inwiefern da noch mal etwas mit der Bank abgestimmt werden muss weiß ich nicht.

**Comment by PatrickHuetter** [comment]
Danke für die zahlreichen und schnellen Antworten! Echt nicht schlecht an einem Sonntag Abend :-) Ihr habt mir schon mal gut weitergeholfen.
@shred wie macht ihr das mit den TANs? Hinterlegt ihr die Tan-Liste digital in einer Datenbank, oder nutzt ihr mobileTan und habt ein SMS Gateway, dass eure SMS empfängt und an die Software weiterleitet? So ein SMS Gateway kann man sich ja ziemlich einfach selbst bauen mit einem Raspberry Pi.

@scaratec Das wäre mein Plan B gewesen. Ich würde auch die XML Datei generieren und mit einem Bot (Selenium Webdriver und headless Webbrowser (z.B. phantomjs oder chrome mit xvfb) im Webinterface der Deutschen Bank hochladen. Dann gäbe es nur noch die Frage zu klären woher die Tans kommen sollen (siehe meine Frage an @shred ).

**Comment by shred** [comment]
Wir benutzen eine HBCI-Karte mit einer festen PIN, keine TANs.

**Comment by PatrickHuetter** [comment]
@shred Wie darf ich mir das vorstellen? Steckt die HBCI Karte dann in einem Gerät permanent am Rechner/Server angeschlossen?

**Comment by shred** [comment]
So in etwa, mit entsprechender Sicherheits-Dekoration. ;-)

**Comment by willuhn** [comment]
> Danke für die zahlreichen und schnellen Antworten! Echt nicht schlecht
> an einem Sonntag Abend :-) Ihr habt mir schon mal gut weitergeholfen.
> @shred wie macht ihr das mit den TANs?
> Hinterlegt ihr die Tan-Liste digital in einer Datenbank, oder nutzt ihr
> mobileTan und habt ein SMS Gateway, dass eure SMS empfängt und an die
> Software weiterleitet? So ein SMS Gateway kann man sich ja ziemlich
> einfach selbst bauen mit einem Raspberry Pi.

Die beste Alternative zur vollautomatischen Zahlungsabwicklung auf dem
Server ist das Verfahren "Schlüsseldatei". Das ist quasi wie Chipkarte -
aber komplett in Software. Also ohne, dass man dafuer einen Kartenleser
braucht. Stattdessen hat man eine Datei, die die kryptografischen
Schluessel enthaelt.

Allerdings bieten nur wenige Banken dieses Verfahren an.

Gruss
Olaf

**Comment by willuhn** [comment]
Ich mach das Ticket mal zu. Da es eigentlich auch gar kein Issue war sondern eher in die Mailingliste unter https://groups.google.com/forum/?hl=de#!forum/hbci4java gepasst haette.
