### ISSUE TITLE
Buchungsreihenfolge bei Umsatzabfrage

### ISSUE THREAD

**Issue by code-chris** [willuhn/hbci4java#48]
Hallo miteinander,

weiß jemand, ob man sich auf die Reihenfolge der zurückgegebenen Umsatzbuchungen ("KUmsAll") verlassen kann bzw. entspricht diese Reihenfolge der tatsächlichen Buchungsreihenfolge der Bank? In den Datums-Feldern steht ja leider nur ein Datum und keine Uhrzeit... Kann also nicht nachträglich sortieren.

Danke!

**Comment by willuhn** [comment]
Es gibt in HBCI leider keine Uhrzeiten bei Umsatz-Buchungen - die Bank überträgt also auch keine. Die Reihenfolge entspricht genau jener, in der sie von der Bank in den MT940-Daten geliefert wurden.
